import { createClient } from "@/lib/supabase/client";
import type { Quote, QuoteInput, QuoteItem } from "@/app/types/quote";

type QuoteRow = { id:string; quote_number:string; customer_id:string; title:string; quote_date:string; valid_until:string; description:string; status:Quote["status"]; remarks:string; payment_term_days:number; terms:string; created_at:string; quote_items?: ItemRow[] };
type ItemRow = { id:string; position:number; description:string; quantity:number|string; unit:QuoteItem["unit"]; unit_price:number; vat_percentage:QuoteItem["vatRate"] };
const columns="id,quote_number,customer_id,title,quote_date,valid_until,description,status,remarks,payment_term_days,terms,created_at,quote_items(id,position,description,quantity,unit,unit_price,vat_percentage)";
const timeout=10_000;
function mapItem(row:ItemRow):QuoteItem { return { id:row.id,description:row.description,quantity:Number(row.quantity),unit:row.unit,pricePerUnitCents:row.unit_price,vatRate:row.vat_percentage }; }
function mapQuote(row:QuoteRow):Quote { return { id:row.id,number:row.quote_number,customerId:row.customer_id,title:row.title,date:row.quote_date,validUntil:row.valid_until,description:row.description,status:row.status,items:(row.quote_items??[]).sort((a,b)=>a.position-b.position).map(mapItem),remarks:row.remarks,paymentTermDays:row.payment_term_days,terms:row.terms,createdAt:row.created_at }; }
function payload(input:QuoteInput) { return { ...input, items:input.items.map((item,position)=>({ ...item, position })) }; }
function abortable() { return new AbortController(); }
export async function listQuotes() { const controller=abortable(); const id=window.setTimeout(()=>controller.abort(),timeout); try { const {data,error}=await createClient().from("quotes").select(columns).order("created_at",{ascending:false}).abortSignal(controller.signal); if(error) throw new Error(`Offertes laden is niet gelukt: ${error.message}`); return (data??[]).map((row)=>mapQuote(row as QuoteRow)); } catch(reason) { if(controller.signal.aborted) throw new Error("Offertes laden duurt langer dan 10 seconden."); throw reason; } finally { window.clearTimeout(id); } }
export async function getQuoteById(id:string) { const controller=abortable(); const timer=window.setTimeout(()=>controller.abort(),timeout); try { const {data,error}=await createClient().from("quotes").select(columns).eq("id",id).abortSignal(controller.signal).maybeSingle(); if(error) throw new Error(`Offerte laden is niet gelukt: ${error.message}`); return data?mapQuote(data as QuoteRow):undefined; } finally { window.clearTimeout(timer); } }
export async function createQuote(input:QuoteInput) { const {data,error}=await createClient().rpc("create_quote",{payload:payload(input)}).single(); if(error||!data) throw new Error(`Offerte opslaan is niet gelukt${error?`: ${error.message}`:"."}`); const quote=await getQuoteById(data as string); if(!quote) throw new Error("De opgeslagen offerte kon niet worden geladen."); return quote; }
export async function updateQuote(id:string,input:QuoteInput) { const {error}=await createClient().rpc("update_quote",{p_quote_id:id,payload:payload(input)}); if(error) throw new Error(`Offerte bijwerken is niet gelukt: ${error.message}`); const quote=await getQuoteById(id); if(!quote) throw new Error("De bijgewerkte offerte kon niet worden geladen."); return quote; }
export async function deleteQuote(id:string) { const {error}=await createClient().from("quotes").delete().eq("id",id); if(error) throw new Error(`Offerte verwijderen is niet gelukt: ${error.message}`); }
