import { createClient } from "@/lib/supabase/client";
import type { Quote, QuoteInput, QuoteItem, QuoteStatus } from "@/app/types/quote";

type ItemRow = { id:string; position:number; description:string; quantity:number|string; unit:QuoteItem["unit"]; unit_price:number; vat_percentage:QuoteItem["vatRate"] };
type CustomerRow = { id:string; name:string; company_name:string|null };
type QuoteRow = { id:string; quote_number:string; customer_id:string; title:string; quote_date:string; valid_until:string; description:string; status:QuoteStatus; remarks:string; payment_term_days:number; terms:string; created_at:string; quote_items?:ItemRow[]; customer?:CustomerRow|CustomerRow[]|null };
export type QuoteStatusHistory = { id:string; quoteId:string; oldStatus:QuoteStatus|null; newStatus:QuoteStatus; note:string; createdAt:string };
export type QuoteWithCustomer = Quote & { customerName:string; customerCompany:string };
export type QuoteFilters = { status?:QuoteStatus|""; customerId?:string; dateFrom?:string; dateTo?:string; sort?:"newest"|"oldest"|"number"|"total-desc"|"total-asc" };
const columns="id,quote_number,customer_id,title,quote_date,valid_until,description,status,remarks,payment_term_days,terms,created_at,quote_items(id,position,description,quantity,unit,unit_price,vat_percentage),customer:customers(id,name,company_name)";
const timeout=10_000;
const mapItem=(row:ItemRow):QuoteItem=>({id:row.id,description:row.description,quantity:Number(row.quantity),unit:row.unit,pricePerUnitCents:row.unit_price,vatRate:row.vat_percentage});
function mapQuote(row:QuoteRow):QuoteWithCustomer { const customer=Array.isArray(row.customer)?row.customer[0]:row.customer; return {id:row.id,number:row.quote_number,customerId:row.customer_id,title:row.title,date:row.quote_date,validUntil:row.valid_until,description:row.description,status:row.status,items:(row.quote_items??[]).sort((a,b)=>a.position-b.position).map(mapItem),remarks:row.remarks,paymentTermDays:row.payment_term_days,terms:row.terms,createdAt:row.created_at,customerName:customer?.name??"Onbekende klant",customerCompany:customer?.company_name??""}; }
const payload=(input:QuoteInput)=>({...input,items:input.items.map((item,position)=>({...item,position}))});
async function timed<T>(request: PromiseLike<T>, message:string) { let timer:number|undefined; try { return await Promise.race([request, new Promise<T>((_,reject)=>{timer=window.setTimeout(()=>reject(new Error(message)),timeout);})]); } finally { if(timer) window.clearTimeout(timer); } }
export async function listQuotes(filters:QuoteFilters={}) {
  let query=createClient().from("quotes").select(columns).order("created_at",{ascending:filters.sort!=="oldest"});
  if(filters.status) query=query.eq("status",filters.status); if(filters.customerId) query=query.eq("customer_id",filters.customerId); if(filters.dateFrom) query=query.gte("quote_date",filters.dateFrom); if(filters.dateTo) query=query.lte("quote_date",filters.dateTo);
  const {data,error}=await timed(query,"Offertes laden duurt langer dan 10 seconden.");
  if(error) throw new Error(`Offertes laden is niet gelukt: ${error.message}`);
  return (data??[]).map((row)=>mapQuote(row as unknown as QuoteRow));
}
export async function getQuoteById(id:string) { const {data,error}=await timed(createClient().from("quotes").select(columns).eq("id",id).maybeSingle(),"Offerte laden duurt langer dan 10 seconden."); if(error) throw new Error(`Offerte laden is niet gelukt: ${error.message}`); return data?mapQuote(data as unknown as QuoteRow):undefined; }
export async function createQuote(input:QuoteInput) { const {data,error}=await timed(createClient().rpc("create_quote",{payload:payload(input)}).single(),"Offerte opslaan duurt langer dan 10 seconden."); if(error||!data) throw new Error(`Offerte opslaan is niet gelukt${error?`: ${error.message}`:"."}`); const quote=await getQuoteById(data as string); if(!quote) throw new Error("De opgeslagen offerte kon niet worden geladen."); return quote; }
export async function updateQuote(id:string,input:QuoteInput) { const {error}=await timed(createClient().rpc("update_quote",{p_quote_id:id,payload:payload(input)}),"Offerte bijwerken duurt langer dan 10 seconden."); if(error) throw new Error(`Offerte bijwerken is niet gelukt: ${error.message}`); const quote=await getQuoteById(id); if(!quote) throw new Error("De bijgewerkte offerte kon niet worden geladen."); return quote; }
export async function deleteQuote(id:string) { const {error}=await timed(createClient().from("quotes").delete().eq("id",id),"Offerte verwijderen duurt langer dan 10 seconden."); if(error) throw new Error(`Offerte verwijderen is niet gelukt: ${error.message}`); }
export async function duplicateQuote(id:string) { const {data,error}=await timed(createClient().rpc("duplicate_quote",{p_quote_id:id}).single(),"Offerte dupliceren duurt langer dan 10 seconden."); if(error||!data) throw new Error(`Offerte dupliceren is niet gelukt${error?`: ${error.message}`:"."}`); return data as string; }
export async function changeQuoteStatus(id:string,status:QuoteStatus,note:string) { const {error}=await timed(createClient().rpc("change_quote_status",{p_quote_id:id,p_new_status:status,p_note:note||null}),"Status wijzigen duurt langer dan 10 seconden."); if(error) throw new Error(`Status wijzigen is niet gelukt: ${error.message}`); }
export async function listQuoteStatusHistory(id:string) { const {data,error}=await timed(createClient().from("quote_status_history").select("id,quote_id,old_status,new_status,note,created_at").eq("quote_id",id).order("created_at",{ascending:false}),"Statusgeschiedenis laden duurt langer dan 10 seconden."); if(error) throw new Error(`Statusgeschiedenis laden is niet gelukt: ${error.message}`); return (data??[]).map((row)=>({id:row.id,quoteId:row.quote_id,oldStatus:row.old_status as QuoteStatus|null,newStatus:row.new_status as QuoteStatus,note:row.note??"",createdAt:row.created_at})); }
export async function countQuotesForCustomer(customerId:string) { const {count,error}=await timed(createClient().from("quotes").select("id",{count:"exact",head:true}).eq("customer_id",customerId),"Offertes tellen duurt langer dan 10 seconden."); if(error) throw new Error(`Offertes tellen is niet gelukt: ${error.message}`); return count??0; }
