"use client";

import Link from "next/link";
import { useState } from "react";
import type { FormEvent } from "react";
import { useCustomers } from "@/app/hooks/use-customers";
import { centsToEuro, formatCurrency, lineTotalCents, parseEuroToCents, quoteTotals } from "@/app/lib/quote-calculations";
import { quoteStatuses, units } from "@/app/types/quote";
import type { QuoteInput, QuoteItem } from "@/app/types/quote";

const inputClass = "mt-1.5 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-950 shadow-sm outline-none focus:border-blue-700 focus:ring-2 focus:ring-blue-100";
const today = () => new Date().toISOString().slice(0, 10);
const fourteenDaysFromNow = () => { const date = new Date(); date.setDate(date.getDate() + 14); return date.toISOString().slice(0, 10); };
const createItem = (): QuoteItem => ({ id: typeof crypto !== "undefined" && crypto.randomUUID ? crypto.randomUUID() : `regel-${Date.now()}`, description: "", quantity: 1, unit: "uur", pricePerUnitCents: 0, vatRate: 21 });
export const createEmptyQuote = (): QuoteInput => ({ customerId: "", title: "", date: today(), validUntil: fourteenDaysFromNow(), description: "", status: "Concept", items: [createItem()], remarks: "", paymentTermDays: 14, terms: "" });

type Props = { initialValues?: QuoteInput; submitLabel: string; onSubmit: (input: QuoteInput) => void };
export function QuoteForm({ initialValues = createEmptyQuote(), submitLabel, onSubmit }: Props) {
  const customers = useCustomers();
  const [values, setValues] = useState<QuoteInput>(initialValues);
  const [priceInputs, setPriceInputs] = useState<Record<string, string>>(() => Object.fromEntries(initialValues.items.map((item) => [item.id, item.pricePerUnitCents ? centsToEuro(item.pricePerUnitCents) : ""])));
  const [errors, setErrors] = useState<{ customerId?: string; title?: string; items?: string; price?: string }>({});
  const customer = customers.find((item) => item.id === values.customerId);
  const totals = quoteTotals(values.items);
  const update = <K extends keyof QuoteInput>(key: K, value: QuoteInput[K]) => setValues((current) => ({ ...current, [key]: value }));
  const updateItem = <K extends keyof QuoteItem>(id: string, key: K, value: QuoteItem[K]) => setValues((current) => ({ ...current, items: current.items.map((item) => item.id === id ? { ...item, [key]: value } : item) }));
  function commitPrice(id: string) { const parsed = parseEuroToCents(priceInputs[id] ?? ""); if (parsed !== null) updateItem(id, "pricePerUnitCents", parsed); }
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const savedItems = values.items.map((item) => ({ ...item, pricePerUnitCents: parseEuroToCents(priceInputs[item.id] ?? "") })); const invalidPrice = savedItems.some((item) => item.pricePerUnitCents === null); const nextErrors = { customerId: !values.customerId ? "Kies een klant." : undefined, title: !values.title.trim() ? "Vul een titel in." : undefined, items: values.items.length === 0 ? "Voeg minimaal één offertregel toe." : undefined, price: invalidPrice ? "Vul voor iedere regel een geldige prijs in, bijvoorbeeld 49,95." : undefined }; setErrors(nextErrors); if (!nextErrors.customerId && !nextErrors.title && !nextErrors.items && !nextErrors.price) onSubmit({ ...values, items: savedItems as QuoteItem[], title: values.title.trim(), description: values.description.trim(), remarks: values.remarks.trim(), terms: values.terms.trim() }); }
  if (customers.length === 0) return <div className="rounded-xl border border-amber-200 bg-amber-50 p-6 text-sm text-amber-900"><h2 className="text-lg font-semibold">Nog geen klanten beschikbaar</h2><p className="mt-2">Voeg eerst een klant toe voordat u een offerte kunt maken.</p><Link className="mt-4 inline-flex rounded-lg bg-blue-700 px-4 py-2.5 font-semibold text-white" href="/klanten/nieuw">Nieuwe klant toevoegen</Link></div>;
  return <form className="space-y-8" noValidate onSubmit={submit}>
    <section><h2 className="text-lg font-semibold text-slate-950">Klant</h2><div className="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-4"><label><span className="text-sm font-medium text-slate-700">Selecteer klant <span className="text-red-600">*</span></span><select aria-invalid={Boolean(errors.customerId)} className={inputClass} onChange={(event) => { update("customerId", event.target.value); setErrors((current) => ({ ...current, customerId: undefined })); }} value={values.customerId}><option value="">Kies een klant</option>{customers.map((item) => <option key={item.id} value={item.id}>{item.name}{item.company ? ` — ${item.company}` : ""}</option>)}</select></label>{errors.customerId && <p className="mt-2 text-sm text-red-700">{errors.customerId}</p>}{customer && <div className="mt-4 grid gap-1 text-sm text-slate-600"><p className="font-medium text-slate-950">{customer.name}{customer.company ? ` · ${customer.company}` : ""}</p><p>{customer.streetAndNumber}, {customer.postalCode} {customer.city}</p><p>{customer.email}</p></div>}</div></section>
    <section><h2 className="text-lg font-semibold text-slate-950">Offertegegevens</h2><div className="mt-4 grid gap-5 sm:grid-cols-2"><label className="sm:col-span-2"><span className="text-sm font-medium text-slate-700">Titel <span className="text-red-600">*</span></span><input aria-invalid={Boolean(errors.title)} className={inputClass} onChange={(event) => { update("title", event.target.value); setErrors((current) => ({ ...current, title: undefined })); }} value={values.title} />{errors.title && <p className="mt-2 text-sm text-red-700">{errors.title}</p>}</label><label><span className="text-sm font-medium text-slate-700">Datum</span><input className={inputClass} onChange={(event) => update("date", event.target.value)} type="date" value={values.date} /></label><label><span className="text-sm font-medium text-slate-700">Geldig tot</span><input className={inputClass} onChange={(event) => update("validUntil", event.target.value)} type="date" value={values.validUntil} /></label><label><span className="text-sm font-medium text-slate-700">Status</span><select className={inputClass} onChange={(event) => update("status", event.target.value as QuoteInput["status"])} value={values.status}>{quoteStatuses.map((status) => <option key={status}>{status}</option>)}</select></label><label><span className="text-sm font-medium text-slate-700">Betalingstermijn (dagen)</span><input className={inputClass} min="0" onChange={(event) => update("paymentTermDays", Number(event.target.value) || 0)} type="number" value={values.paymentTermDays} /></label><label className="sm:col-span-2"><span className="text-sm font-medium text-slate-700">Omschrijving werkzaamheden</span><textarea className={inputClass} onChange={(event) => update("description", event.target.value)} rows={4} value={values.description} /></label></div></section>
    <section><div className="flex items-center justify-between gap-4"><h2 className="text-lg font-semibold text-slate-950">Offertregels</h2><button className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50" onClick={() => { const item = createItem(); update("items", [...values.items, item]); setPriceInputs((current) => ({ ...current, [item.id]: "" })); }} type="button">Regel toevoegen</button></div>{errors.items && <p className="mt-2 text-sm text-red-700">{errors.items}</p>}{errors.price && <p className="mt-2 text-sm text-red-700">{errors.price}</p>}<div className="mt-4 space-y-4">{values.items.map((item, index) => <div className="rounded-xl border border-slate-200 bg-slate-50 p-4" key={item.id}><div className="grid gap-3 sm:grid-cols-12 sm:items-end"><label className="sm:col-span-4"><span className="text-xs font-medium text-slate-600">Omschrijving</span><input className={inputClass} onChange={(event) => updateItem(item.id, "description", event.target.value)} value={item.description} /></label><label className="sm:col-span-2"><span className="text-xs font-medium text-slate-600">Aantal</span><input className={inputClass} min="0" onChange={(event) => updateItem(item.id, "quantity", Number(event.target.value) || 0)} step="0.01" type="number" value={item.quantity} /></label><label className="sm:col-span-2"><span className="text-xs font-medium text-slate-600">Eenheid</span><select className={inputClass} onChange={(event) => updateItem(item.id, "unit", event.target.value as QuoteItem["unit"])} value={item.unit}>{units.map((unit) => <option key={unit}>{unit}</option>)}</select></label><label className="sm:col-span-2"><span className="text-xs font-medium text-slate-600">Prijs p.e.</span><input className={inputClass} inputMode="decimal" onBlur={() => commitPrice(item.id)} onChange={(event) => { setPriceInputs((current) => ({ ...current, [item.id]: event.target.value })); setErrors((current) => ({ ...current, price: undefined })); }} placeholder="0,00" value={priceInputs[item.id] ?? ""} /></label><label className="sm:col-span-1"><span className="text-xs font-medium text-slate-600">Btw</span><select className={inputClass} onChange={(event) => updateItem(item.id, "vatRate", Number(event.target.value) as QuoteItem["vatRate"])} value={item.vatRate}>{[0, 9, 21].map((rate) => <option key={rate} value={rate}>{rate}%</option>)}</select></label><div className="sm:col-span-1"><button aria-label={`Regel ${index + 1} verwijderen`} className="w-full rounded-lg px-2 py-2.5 text-sm font-medium text-red-700 hover:bg-red-50 disabled:text-slate-300" disabled={values.items.length === 1} onClick={() => update("items", values.items.filter((current) => current.id !== item.id))} type="button">×</button></div></div><p className="mt-3 text-right text-sm font-medium text-slate-700">Regeltotaal: {formatCurrency(lineTotalCents(item))}</p></div>)}</div></section>
    <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold text-slate-950">Berekening</h2><dl className="mt-4 space-y-2 text-sm"><div className="flex justify-between"><dt className="text-slate-600">Subtotaal excl. btw</dt><dd>{formatCurrency(totals.subtotalCents)}</dd></div>{totals.vatByRate.filter((vat) => vat.cents > 0 || values.items.some((item) => item.vatRate === vat.rate)).map((vat) => <div className="flex justify-between" key={vat.rate}><dt className="text-slate-600">Btw {vat.rate}%</dt><dd>{formatCurrency(vat.cents)}</dd></div>)}<div className="flex justify-between border-t border-slate-200 pt-3 text-base font-semibold"><dt>Totaal incl. btw</dt><dd>{formatCurrency(totals.totalCents)}</dd></div></dl></section>
    <section><h2 className="text-lg font-semibold text-slate-950">Extra gegevens</h2><div className="mt-4 grid gap-5"><label><span className="text-sm font-medium text-slate-700">Opmerkingen</span><textarea className={inputClass} onChange={(event) => update("remarks", event.target.value)} rows={3} value={values.remarks} /></label><label><span className="text-sm font-medium text-slate-700">Algemene voorwaarden of slottekst</span><textarea className={inputClass} onChange={(event) => update("terms", event.target.value)} rows={4} value={values.terms} /></label></div></section>
    <button className="rounded-lg bg-blue-700 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-blue-800" type="submit">{submitLabel}</button>
  </form>;
}
